alias dkup='docker-compose up -d && docker attach $(docker-compose ps | tail -n1 | cut -d" " -f1)'
alias dk='docker'
alias dkc='docker-compose'

alias cdup='cd ../'
alias subl='subl .'
alias atom-o='open -a "Atom" .'
alias atom='atom .'

alias gchp='git checkout -'
alias gchm='git checkout master'
alias gch='git checkout'
alias gstat='git status'
alias gdiff='git diff'
alias gcam='git commit -am'
alias gcav='git commit -av'
alias gcavp='git commit -av && git push'
alias gadd='git add -A'
alias gpush='git push'
alias gpull='git pull'
alias gstash='git stash'

alias opnb='op new-branch'
alias oppr='op pull-request'
alias opsu='op stage-up'
alias opap='op accept-pull'
alias optg='op tag-release'

alias gd='gordy deploy -u'
alias gdd='gordy deploy -ud'
alias gds='gordy deploy -u -e staging'
alias gdsd='gordy deploy -du -e staging'
alias gdp='gordy deploy -u -e production'
alias gdpd='gordy deploy -du -e production'

alias soyuz-dep='soyuz deploy'
alias add-ssh='ls ~/.ssh/*.pub | sed 's/.pub//' | xargs ssh-add -K'

alias opsms='opsicle monitor staging'
alias opsmp='opsicle monitor production'
alias opsis='opsicle instances staging'
alias opsip='opsicle instances production'
alias opsss='opsicle ssh staging'
alias opssp='opsicle ssh production'
alias opscis='opsicle clone-instance staging'
alias opscip='opsicle clone-instance production'
alias opssis='opsicle stop-instance staging'
alias opssip='opsicle stop-instance production'
alias opsdis='opsicle delete-instance staging'
alias opsdip='opsicle delete-instance production'
alias opsmeips='opsicle move-eip staging'
alias opsmeipp='opsicle move-eip production'
alias opsads='opsicle add-tags staging'
alias opsadp='opsicle add-tags production'

alias cleangit='git fetch -p && for branch in `git branch -vv | grep ": gone]" | awk '"'"'{print $1}'"'"'`; do git branch -D $branch; done'
export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future
export NVM_DIR="/Users/emmasax/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# added by travis gem
[ -f /Users/emmasax/.travis/travis.sh ] && source /Users/emmasax/.travis/travis.sh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

